### ISSUE TITLE
Permission based redirect on login

### ISSUE THREAD

**Issue by kodepareek** [marmelab/aor-permissions#24]
Hi Guys.

This is in reference to this issue https://github.com/marmelab/aor-permissions/issues/9

Have been trying this for a while today with this saga on login.

```
const permission = localStorage.getItem('permissions')

function* userLoginSuccess() {
  if (permission === 'publishing') {
    yield put(push('/tales'))
  } else {
    yield put(push('/tales/talesByRelation'))
  }
}

export default function* userLoginSaga() {
  yield all ([
    takeEvery('AOR/USER_LOGIN_SUCCESS', userLoginSuccess),
  ])
}

```
But no redirect happens. I get a warning from the SwitchPermissionsComponent

`
setState(…): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op

`
Please do advise.

**Comment by djhi** [comment]
Hi, and thanks for your question. The right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/admin-on-rest).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/admin-on-rest

And once you get a response, please continue to hang out on the admin-on-rest channel in StackOverflow. That way, you can help newcomers and share your expertise!
